name: rlif
channels:
    - defaults
    - nvidia
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy=1.22.4
    - scipy
    - h5py
    - matplotlib
    - scikit-learn
    - jupyter
    - tqdm
    - seaborn
    - Cython=0.29.34
    - jax=0.4.10
    - jaxlib=0.4.10=*cuda*
    - cudatoolkit=11.8.0
    - cuda-nvcc=11.4.152
    - cudnn
    - pip:
      - chex==0.1.7
      - flax==0.6.11
      - optax==0.1.5
      - distrax==0.1.3
      - gym==0.23.1
      - jax-jumpy==1.0.0
      - orbax-checkpoint==0.2.3
      - gymnasium==0.29.0
      - gymnasium-robotics==1.2.2
      - absl-py
      - git+https://github.com/Farama-Foundation/D4RL.git@2b96431a0e9fd90c8032624b0dc3cd4514d15632
      - wandb
      - ml_collections
      - tensorflow==2.12.0
      - tensorflow-probability==0.19.0
      - tensorflow-estimator==2.12.0
      - tensorboardX